default_platform(:android)

platform :android do
  desc "Upload the dev release APK to Firebase App Distribution"
  lane :firebase_app_distribution_release do |options|
    UI.message("Distributing dev build #{options[:build_number]}")

    firebase_app_distribution(
      app: ENV.fetch("FIREBASE_APP_ID_DEV"),
      service_credentials_file: ENV.fetch("FIREBASE_SERVICE_CREDENTIALS_FILE"),
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-dev-release.apk",
      groups: "testers",
      release_notes: ENV["RELEASE_NOTES"]
    )
  end
end
